pipeline {
    agent any
    // agent {
    //     docker {
    //         image 'maven:3.9.0'
    //         args '-v /root/.m2:/root/.m2'
    //     }
    // }    
    stages {
        stage ('Say Bonjour') {
            steps{
                echo "Bonjour"
            }            
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                //sh './jenkins/scripts/deliver.sh'
                echo 'Deliver'
            }
        }

        stage('Result'){
            steps{
                echo "Check completion with option of Build Triggers: Poll SCM - schedule time"
            }
        }
    }
}
